name: Build and Deploy (GitOps)

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Construimos la imagen usando el SHA del commit como versión única
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ikedaharket/anami-frontend:${{ github.sha }}
          platforms: linux/arm64

      # --- LÓGICA DE SEPARACIÓN DE ENTORNOS ---
      - name: Update Infrastructure Repo
        run: |
          # 1. Determinar el directorio objetivo según la rama
          if [ "${{ github.ref_name }}" == "main" ]; then
            TARGET_DIR="tenants/anami/prod/frontend"
            ENV_NAME="PROD"
          else
            TARGET_DIR="tenants/anami/qa/frontend"
            ENV_NAME="QA"
          fi

          # 2. Clonar repo de infra
          git config --global user.email "bot@ikedadev.com"
          git config --global user.name "IkedaDev Bot"
          git clone https://x-access-token:${{ secrets.INFRA_REPO_TOKEN }}@github.com/ikedaharket/ikedadev-infra.git
          cd ikedadev-infra

          # 3. Actualizar la imagen en el YAML correspondiente
          # Buscamos la línea 'image:' y reemplazamos todo lo que venga después por la nueva versión
          sed -i "s|image: ikedaharket/anami-frontend:.*|image: ikedaharket/anami-frontend:${{ github.sha }}|g" ${TARGET_DIR}/deployment.yaml

          # 4. Commit y Push
          git add .
          git commit -m "chore($ENV_NAME): update image to ${{ github.sha }} from branch ${{ github.ref_name }}"
          git push
